# Main game data
FPS = 60
WIDTH, HEIGHT = 620, 740


# Values specific to the sandtris
GAME_SCREEN_WIDTH, GAME_SCREEN_HEIGHT = 300, 690
GRAIN_SIZE = 3
ROWS = GAME_SCREEN_HEIGHT // GRAIN_SIZE
COLS = GAME_SCREEN_WIDTH // GRAIN_SIZE

PIECE_SIZE = 30
CHUNK_SIZE = 10
