# Main game data
FPS = 0
WIDTH, HEIGHT = 620, 740


# Values specific to the sandtris
GAME_SCREEN_WIDTH, GAME_SCREEN_HEIGHT = 330, 690
GRAIN_SIZE = 3
ROWS = GAME_SCREEN_HEIGHT // GRAIN_SIZE
COLS = GAME_SCREEN_WIDTH // GRAIN_SIZE

PIECE_SIZE = 30
CHUNK_SIZE = 10

POINTS_PER_GRAIN = 0.01

COLOURS = ["black", "red", "green", "blue", "yellow"]
